"""create users table and roles table

Revision ID: b9464990fb63
Revises: 5152accf8e88
Create Date: 2025-05-06 14:26:43.998963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision: str = 'b9464990fb63'
down_revision: Union[str, None] = '5152accf8e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_updated_at'), 'roles', ['updated_at'], unique=False)
    op.create_primary_key('pk_roles', 'roles', ['id'])
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('password', sa.String(length=100), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_primary_key('pk_users', 'users', ['id'])
    op.create_foreign_key('fk_users_role_id', 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    roles_data = table(
        'roles',
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('code', sa.String),
        sa.Column('created_at', sa.DateTime),
        sa.Column('updated_at', sa.DateTime)
    )

    op.bulk_insert(
        roles_data,
        [
            {
                'id': 1,
                'name': '管理者',
                'code': 'ADMIN',
                'created_at': '2025-05-06 14:26:43.998963',
                'updated_at': '2025-05-06 14:26:43.998963'
            },
            {
                'id': 2,
                'name': '一般ユーザー',
                'code': 'USER',
                'created_at': '2025-05-06 14:26:43.998963',
                'updated_at': '2025-05-06 14:26:43.998963'
            }
        ]
    )

    users_data = table(
        'users',
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('password', sa.String),
        sa.Column('role_id', sa.Integer),
        sa.Column('created_at', sa.DateTime),
        sa.Column('updated_at', sa.DateTime),
        sa.Column('deleted_at', sa.DateTime)
    )

    op.bulk_insert(
        users_data,
        [
            {
                'id': 1,
                'name': 'admin_1a3bc', # 実運用では異なるユーザー名に変更
                'password': 'admin', # テストデータ
                'role_id': 1,
                'created_at': '2025-05-06 14:26:43.998963',
                'updated_at': '2025-05-06 14:26:43.998963',
                'deleted_at': None
            },
            {
                'id': 2,
                'name': 'user_1a3bc', # 実運用では異なるユーザー名に変更
                'password': 'user', # テストデータ
                'role_id': 2,
                'created_at': '2025-05-06 14:26:43.998963',
                'updated_at': '2025-05-06 14:26:43.998963',
                'deleted_at': None
            }
        ]
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_primary_key('pk_users', 'users')
    op.drop_constraint('fk_users_role_id', 'users', type_='foreignkey')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_roles_updated_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_primary_key('pk_roles', 'roles')
    # ### end Alembic commands ###
